### PR TITLE
Added fix to get time data into the log entity. 

### PR DESCRIPTION
**Pull request by DreamWver**
Previous code used java.sql.Date type for log database rows, which tosses time information. 
Now using timestamp to support sorting of announcements by date **and** time.

### CODE REVIEW

**Review by tparkergh — APPROVED** [review]
Forgot how verbose Java can be. Looks good

**Review by comeara — APPROVED** [review]
👍

**Comment by comeara** [comment]
@DreamWver Does this need to be merged for the next release?

**Comment by DreamWver** [comment]
It needs to be merged with the nics-web changes that should be receiving a
pull request soon. So I think the answer is yes.

Terry J Weaver
Ph: 916.715.6969
terry.j.weaver@gmail.com

**Comment by DreamWver** [comment]
I take it back after the sprint planning this morning. The UI won't be changed on this release, so don't merge yet.

**Pull request merged**
